### ISSUE TITLE
Landing asset to be changed

### ISSUE THREAD

**Issue by karx** [karx/vidiyo-frontpage#2]
To be provided by chitransh.

**Comment by Chitranshmittal** [comment]
Celebrities in the world of entertainment are the face of our nation. All the renowned artists and sports heroes need help in taking care of their business negotiations as brand ambassadors. Our team identifies talents in aspiring and already rocking artists to endorse their shout-out video for the targeted consumer in the market. 

Our celebrity managers have a wonderful relationship with the rich and the famous in the world of fashion, movies and sports. Our clientele is satisfied and happy and the list is growing. Our managers are focused and always take new challenges to greater heights. 

Our syndication process doesn't only include coordination of the Artists but also involves planning, security, taking permissions and technical knowledge. We believe in delivering happiness to those who deserve them and work closely with a variety of foundations which believe in changing the world and make it a better place. By using Vidyo, you are contributing to bringing smiles to those who need it.

**Comment by karx** [comment]
Can we have this in a script format as well for a short video about syndication/enrolling?
This video to show how a talent can utilize vidiyo platform.

- how to get started (enrolling -> contract plan)
- how to fulfil the request (we show that watermark and ... added)

**Comment by karx** [comment]
![image](https://user-images.githubusercontent.com/7826138/64772006-86ba0400-d56d-11e9-9132-5ccd938a6b80.png)

**Comment by karx** [comment]
closing.
